# name: Generate pacman animation

# on:
#   schedule: # execute every 12 hours
#     - cron: "* */12 * * *"

#   workflow_dispatch:

#   push:
#     branches:
#     - main

# jobs:
#   generate:
#     permissions:
#       contents: write
#     runs-on: ubuntu-latest
#     timeout-minutes: 5

#     steps:
#       - name: generate pacman-contribution-graph.svg
#         uses: abozanona/pacman-contribution-graph@main
#         with:
#           github_user_name: ${{ github.repository_owner }}


#       - name: push pacman-contribution-graph.svg to the output branch
#         uses: crazy-max/ghaction-github-pages@v3.1.0
#         with:
#           target_branch: output
#           build_dir: dist
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
name: Generate pacman animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5

    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Generate Pacman SVG
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Debug - List all files
        run: find . -type f

      - name: Move SVG to output folder
        run: |
          mkdir -p output
          mv dist/pacman-contribution-graph.svg output/pacman-contribution-graph.svg
      - name: Pull latest changes from remote
        run: git pull origin main
       
      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add output/
          git commit -m "update pacman graph" || echo "No changes"
       
          git push
