name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"  # every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: snake.svg?palette=github-dark

      - name: Move generated snake.svg to output folder
        run: |
          mkdir -p output
          mv snake.svg output/snake.svg

      - name: Commit and push to main
        run: |
          git config user.name meltingsemicolon
          git config user.email 172062859+meltingsemicolon@users.noreply.github.com
          git add output/snake.svg
          git commit -m "update snake svg" || echo "No changes to commit"
          git push -f
